version: '3.8'

services:
  app:
    command: serve -s dist -l 3000
    image: homepage
    build:
      context: .
    volumes:
      - ./homepage:/homepage
    environment:
      - DEBUG=1
      - DJANGO_SECRET_KEY=654564ytffff55474fjddgdg
      - POSTGRES_HOST=apidb
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
